name: next_hour
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  http: ^0.12.0
  path_provider: ^1.2.0
  validate: ^1.7.0
  connectivity: ^0.3.2
  flutter_swiper: ^1.1.4
  chewie: ^0.9.7
  flutube: ^0.7.3
  bubble_tab_indicator: "^0.1.4"
  shimmer: ^1.0.0
  sticky_headers: ^0.1.8
  fluttertoast: ^3.1.3
  flutter_html: ^0.10.4
  intro_slider: ^2.2.5
  webview_flutter: ^0.3.10+4
  font_awesome_flutter: ^8.5.0
  flutter_datetime_picker: 1.2.6
  image_picker: 0.6.1+2
  launch_review: 2.0.0
  share: 0.6.2+1
  stripe_api: ^1.1.0
  intl: ^0.15.8
  charts_flutter: ^0.5.0
  flutter_credit_card:
  onesignal_flutter: ^2.0.2
  shared_preferences: 0.5.3+4
  braintree_payment: ^1.2.2
  dio: ^2.1.16
  seekbar: ^0.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_paystack: 1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/placeholder_cover.jpg
     - assets/placeholder_box.jpg
     - assets/logo.png
     - assets/stripe.png
     - assets/map.png
     - icons/amex.png
     - icons/discover.png
     - icons/mastercard.png
     - icons/visa2.png
     - assets/avatar.png
     - assets/braintreewallet.png
     - assets/paystackwallets.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
        - family: Lato
          fonts:
            - asset: fonts/Lato-Regular.ttf
            - asset: fonts/Lato-Medium.ttf
              weight: 500
            - asset: fonts/Lato-Semibold.ttf
              weight: 600
            - asset: fonts/Lato-Black.ttf
              weight: 900
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
